# Atelier 1 : recharger data/offres.ndjson dans l'index "offres" du TP.
input {
  file {
    # TODO 1 : lire le fichier entièrement, une seule fois (pas en suivi continu) — voir le
    #          tableau "Mode" de l'énoncé (entrée file, mode read vs tail)
    path => "/data/offres*.ndjson"
    mode => "read" 
    file_completed_action => "log"
    file_completed_log_path => "/usr/share/logstash/data/offres_lus.log"
    codec => "json"
    sincedb_path => "/dev/null"
  }
}

filter {
    mutate {
      remove_field => [ "@timestamp", "event", "host", "@version", "log" ]
    }
  }
  # TODO 6 (exercice 1.3, à traiter après avoir observé l'erreur d'indexation) :
  # avec un filtre mutate, supprimer les champs ajoutés par Logstash que le mapping
  # "dynamic": "strict" de l'index "offres" refuse.


output {
  elasticsearch {
    hosts => ["${ES_HOSTS}"]
    user => "${ES_USER}"
    password => "${ES_PASSWORD}"
    index => "offres"
    document_id => "%{id}"
    data_stream => "false"
    action => "index"
    manage_template => "false"

    # TODO 5 : index cible "offres" ; _id du document = champ "id" de l'offre (ingestion
    #          idempotente) ; action "index" ; pas de data stream ; pas de gestion de template
    #          (le mapping existe déjà, TP d'introduction exercice 1.4)
  }
}
